services:
  app:
    build: .
    #image: go-paste-it:local
    container_name: go-paste-it
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - data:/data
    environment:
      - PASTE_DATA_DIR=/data
#      - PASTE_BASE_URL=https://paste.example.com

volumes:
  data:
