name: Release Lambda Function

on:
  push:
    branches:
      - production

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      lambda: write
      logs: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Install AWS CLI and zip
        run: |
          sudo apt-get update && sudo apt-get -y install awscli zip

      - name: Build Go binary for Lambda
        run: |
          GOOS=linux GOARCH=amd64 go build -o bootstrap main.go

      - name: Prepare deployment package (zip)
        run: |
          zip -r deployment.zip bootstrap templates static

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy to AWS Lambda
        run: |
          aws lambda update-function-code \
            --function-name ${{ secrets.LAMBDA_FUNCTION_NAME }} \
            --zip-file fileb://deployment.zip
