name: Build and Release Lambda Package

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*L'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'

      - name: Build Go binary for Lambda
        run: |
          GOOS=linux GOARCH=amd64 go build -o bootstrap .

      - name: Prepare deployment package
        run: |
          mkdir lambda_package
          mv bootstrap lambda_package/
          cp -r static lambda_package/
          cp -r templates lambda_package/
          cd lambda_package
          branchname=$(echo "${GITHUB_REF##*/}")
          zip -r "../go-paste-it_${branchname}.zip" .

      - name: Upload release asset
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: go-paste-it_${{ github.ref_name }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
